### PR TITLE
Add TravisCI

### PR DESCRIPTION
**Pull request by npyl**
Add TravisCI so that we know if the script works out-of-the-box on a brand new installation!

### CODE REVIEW

**Comment by wjk** [comment]
Welcome @npyl, and thanks for your contribution! Could you please rebase it off of the current `master` branch? I pushed some material changes to the build system just now. Also, do you have "Allow edits from maintainers" turned on for this PR? (I can't see this for myself, unfortunately.) If so, I would like to make a few edits to your script to make it more robust before it is merged. Thanks again!

**Comment by npyl** [comment]
Hi! @wjk Its great contributing to this project :) .  I can rebase but how do I reapply the patches? Do I have to re-apply them manually one-by-one? ~I will checkout "Allow edits from maintainers" and see if i can enable it ;)~ It is actually enabled!

**Comment by wjk** [comment]
Unfortunately, I noticed that you made this PR from the `master` branch of your fork. This is a problem, as it means that we cannot rebase your PR on top of the new tip of the master branch. GitHub best practice recommends that all PRs be made off of a _topic branch_: that is, a new branch (not `master`!) that is dedicated to changes made for this PR only. You can have as many topic branches as you want.

Unfortunately, the only way I know of to fix a PR made off of the `master` branch by mistake is to create a new one. You can reapply your patches using the following series of commands:

```shell
git branch travis 0503783 # this is the commit ID of the tip of the branch you are sending the PR into, in this case master
git checkout travis
git cherry-pick 9aba1d9..50c885a # this tells Git to copy the changes between and including these two commit IDs into the new branch
git push -u origin travis # push the new branch to GitHub
```

You can then create a new PR. I am going to close this PR accordingly. Your contribution is valuable, and it will be reviewed in full once the above problems are resolved. Thank you for your contribution!

**Comment by csekel** [comment]
@wjk please merge next time and make changes as you see fit. As this will move along PR faster and @npyl Thank you for your PR.

**Pull request closed without merging**
